example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import create_ajax_wishlist, show_wishlist, show_xml, show_json, show_json_by_id, show_xml_by_id, register, login_user, logout_user, show_ajax, create_ajax_wishlist

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name = 'show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name = 'show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_ajax, name='show_ajax'),
    path('ajax/submit/', create_ajax_wishlist, name='create_ajax_wishlist')
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core import serializers
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from wishlist.models import BarangWishlist

@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data = BarangWishlist.objects.all()
    context = {
    'list_barang': data,
    'nama': 'Alicia Kirana',
    'last_login': request.COOKIES,
}
    return render(request, "wishlist.html", context)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")



# lab 3

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response



# lab 4

@login_required(login_url='/wishlist/login/')
def show_ajax(request):
    context = {
    'nama': 'Alicia Kirana',
    'last_login': request.COOKIES,
}
    return render(request, "wishlist_ajax.html", context)

def create_ajax_wishlist(request):
    if request.method == "POST":
        nama_barang = request.POST.get("nama_barang")
        harga_barang = request.POST.get("harga_barang")
        deskripsi = request.POST.get("deskripsi")

        new_barang = BarangWishlist(
            nama_barang=nama_barang,
            harga_barang=harga_barang,
            deskripsi=deskripsi,
        )
        new_barang.save()
        return HttpResponse(
            serializers.serialize("json", [new_barang]),
            content_type="application/json",
        )

    return HttpResponse("Invalid method", status_code=405)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous">
    
  </script>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}

<div class="p-3 mb-2 bg-dark text-white">
  <ul class="nav justify-content-center p-3 mb-2 bg-dark text-white">
    <li class="nav-item">
      <a class="nav-link active" href="#">{{nama}}</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'wishlist:logout' %}">Logout</a>
    </li>
</ul>

<table class="table table-bordered">
    <tr>
    <th scope="col" class="text-primary">Nama Barang</th>
    <th scope="col" class="text-primary">Harga Barang</th>
    <th scope="col" class="text-primary">Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
    <tr>
        <th class="text-danger">{{barang.nama_barang}}</th>
        <th class="text-warning">{{barang.harga_barang}}</th>
        <th class="text-success">{{barang.deskripsi}}</th>
    </tr>
{% endfor %}
</table>

<h5 class="text-justify">Sesi terakhir login: {{last_login}}</h5>
{% comment %}<button type="button" class="btn btn-danger"><a href="{% url 'wishlist:logout' %}">Logout</a></button>{% endcomment %}

</div>
{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}
<style>
  .table {
    text-align: center;
    margin-top: 20px;
    border-collapse: collapse;
    background-color: #eae2b7;
    color: #023047;
    border: 5px solid #eae2b7;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 20px;
    max-width: 85vw;
  }
</style>
<div class="p-3 mb-2 bg-dark text-white">
  <ul class="nav justify-content-center p-3 mb-2 bg-dark text-white">
    <li class="nav-item">
      <a class="nav-link active" href="#">{{nama}}</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'wishlist:logout' %}">Logout</a>
    </li>
</ul>

<table class = "table">
  <tr>
      <th>Nama Barang</th>
      <th>Harga Barang</th>
      <th>Deskripsi</th>
  </tr>

  {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
  <tbody id="table_data">
  </tbody>
</table>

<div class="form d-flex justify-content-center">
  <div>
    <h4 style = "text-align: center;">Tambah Baru</h4>
    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Nama Barang</td>
                <td><input type="text" id="nama_barang" name="nama_barang" placeholder="Nama Barang" class="form-control">
                </td>
            </tr>

            <tr>
                <td>Harga Barang</td>
                <td><input type="number" id="harga_barang" name="harga_barang" placeholder="Harga Barang" class="form-control"></td>
            </tr>

            <tr>
                <td>Deskripsi</td>
                <td><textarea class="form-control" id="deskripsi" name="deskripsi"></textarea></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn btn-primary" type="submit" value="Submit" id="newBtn"></td>
            </tr>
        </table>
    </form>
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    function postNew(e) {
        e.preventDefault()
        const namaBarang = $("#nama_barang").val()
        const hargaBarang = $("#harga_barang").val()
        const deskripsi = $("#deskripsi").val()

        const data = {
            nama_barang: namaBarang,
            harga_barang: hargaBarang,
            deskripsi,
            csrfmiddlewaretoken: "{{ csrf_token }}"
        }

        $.ajax({
            type: 'POST',
            url: "{% url 'wishlist:create_ajax_wishlist' %}",
            data: data,
            success: () => {
                alert("Data berhasil dibuat!")
                fetchData()
            },
            dataType: 'json'
        });
    }

    function writeTable(data) {
        const table = $("#table_data")
        table.empty()
        for (let i = 0; i < data.length; i++) {
            table.append(`
          <tr>
            <td>${data[i].fields.nama_barang}</td>
            <td>${data[i].fields.harga_barang}</td>
            <td>${data[i].fields.deskripsi}</td>
          </tr>
          `)
        }
    }

    function fetchData() {
        $.get("/wishlist/json", writeTable)
    }

    $(document).ready(() => {
        $("#newBtn").click(postNew)
        fetchData()
    })
</script>
{% endblock content %}